stages:
  - build

# Deploy branches only
deploy:
  script:
    - whoami
    - hostname
    - pwd
    - mvn -v
    - mvn --batch-mode --errors -U clean deploy
  stage: build
  only:
    - branches
  tags:
    - Java8-Nexus3
